name: pantheon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  material_symbols_icons: ^4.2671.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/
